# Simple workflow that just tests the code (no deployment)
name: Test Stock Prediction App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test imports
      run: |
        python -c "
        import sys
        sys.path.append('src')
        try:
            from data_collection import StockDataCollector
            from feature_engineering import FeatureEngineer  
            from model import LSTMStockPredictor
            print('✅ All modules imported successfully!')
        except Exception as e:
            print(f'❌ Error: {e}')
            exit(1)
        "
    
    - name: Test basic functionality
      run: |
        python -c "
        import sys
        sys.path.append('src')
        from data_collection import StockDataCollector
        
        print('Testing data collection...')
        collector = StockDataCollector()
        data = collector.fetch_stock_data('AAPL', period='5d')
        print(f'✅ Successfully fetched {len(data)} rows of AAPL data')
        
        if collector.validate_data(data):
            print('✅ Data validation passed')
        else:
            print('❌ Data validation failed')
            exit(1)
        "
